// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a4cf2ba7bf830b43 "22.design", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'hu'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Menu Iteam' | 'Black' | 'Dropdwon Open' | 'Footer Menu ' // Variant
 * title?: string // Title
 * link?: string // Link
 * iconVisible?: boolean // Icon Visible
 * click?: Function // Click
 * hover?: Function // Hover
}} Props

 */
import { stdin_default } from "../chunks/chunk-7U3YD3A3.js";
import "../chunks/chunk-GEDUOKAR.js";
import { routes } from "../chunks/chunk-YLHGZSRP.js";

// virtual:header/menu-iteam
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "ivosmmTUd",
		name: "Magyar",
		slug: "hu",
		code: "hu-HU",
	},
];
var defaultResponsiveVariants = {
	base: "I10734:318;10716:439",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a4cf2ba7bf830b43e5f8ed2d8a2bf8e971ecc328736008d3116207e22869c77c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MenuIteamFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a4cf2ba7bf830b43e5f8ed2d8a2bf8e971ecc328736008d3116207e22869c77c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var menu_iteam_default = ComponentWithRoot;
export { menu_iteam_default as default };
