// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a4cf2ba7bf830b43 "22.design", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'hu'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
}} Props

 */
import { stdin_default } from "./chunks/chunk-ZK5V2VS4.js";
import { routes } from "./chunks/chunk-YLHGZSRP.js";

// virtual:framer-expert-badge
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qPPOKuGMJdHvopsgBsry/FJePi8t89IEzkZH16xs8/GhJalQe6m.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var FramerBadgeBaseFonts = getFonts(stdin_default);
var serializationHash = "framer-oV4tC";
var variantClassNames = {
	duac4igBe: "framer-v-h6mn92",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, width, ...props }) => {
	return {
		...props,
		JOPNVvApM: link ?? props.JOPNVvApM,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		JOPNVvApM: JOPNVvApM2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "duac4igBe",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-h6mn92",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"duac4igBe"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={26}
							y={
								(componentViewport?.y || 0) +
								(0 + ((componentViewport?.height || 26) - 0 - 26) / 2)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1m7rs3s-container"}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"EIiA_6tYv-container"}
								nodeId={"EIiA_6tYv"}
								rendersWithMotion={true}
								scopeId={"GhJalQe6m"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "EIiA_6tYv",
									layoutId: "EIiA_6tYv",
									mS0YtcEy_: "Official Framer Expert",
									oOze2xTD9: JOPNVvApM2,
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oV4tC.framer-l75qg9, .framer-oV4tC .framer-l75qg9 { display: block; }",
	".framer-oV4tC.framer-h6mn92 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-oV4tC .framer-1m7rs3s-container { flex: none; height: auto; position: relative; width: auto; }",
];
var FramerGhJalQe6m = withCSS(Component, css, "framer-oV4tC");
var stdin_default2 = FramerGhJalQe6m;
FramerGhJalQe6m.displayName = "Framer Expert Badge";
FramerGhJalQe6m.defaultProps = {
	height: 26,
	width: 151.5,
};
addPropertyControls(FramerGhJalQe6m, {
	JOPNVvApM: {
		description: "Your Expert Profile URL. framer.com/@ben/",
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerGhJalQe6m,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...FramerBadgeBaseFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:framer-expert-badge
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "ivosmmTUd",
		name: "Magyar",
		slug: "hu",
		code: "hu-HU",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a4cf2ba7bf830b43e5f8ed2d8a2bf8e971ecc328736008d3116207e22869c77c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FramerExpertBadgeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a4cf2ba7bf830b43e5f8ed2d8a2bf8e971ecc328736008d3116207e22869c77c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var framer_expert_badge_default = ComponentWithRoot;
export { framer_expert_badge_default as default };
