// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a4cf2ba7bf830b43 "22.design", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'hu'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
 * label?: string // Label
}} Props

 */
import { routes } from "./chunks/chunk-YLHGZSRP.js";

// virtual:framer-badge-base-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gDH0362CkgNPhwbEr4wP/k31eowWlunx2Th2qNXJg/eBxbj2ci2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-fEJfj";
var variantClassNames = {
	GOvhpbMxk: "framer-v-9gd1vd",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, label, link, width, ...props }) => {
	return {
		...props,
		mS0YtcEy_: label ?? props.mS0YtcEy_ ?? "Framer Expert",
		oOze2xTD9: link ?? props.oOze2xTD9,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		oOze2xTD9: oOze2xTD92,
		mS0YtcEy_: mS0YtcEy_2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "GOvhpbMxk",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={oOze2xTD92}
						motionChild={true}
						nodeId={"GOvhpbMxk"}
						openInNewTab={true}
						scopeId={"eBxbj2ci2"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-9gd1vd", className, classNames)} framer-1nbf37q`}
							data-border={true}
							data-framer-name={"Dark"}
							layoutDependency={layoutDependency}
							layoutId={"GOvhpbMxk"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(255, 255, 255, 0.2)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgb(0, 0, 0)",
								borderBottomLeftRadius: 7,
								borderBottomRightRadius: 7,
								borderTopLeftRadius: 7,
								borderTopRightRadius: 7,
								...style,
							}}
						>
							<SVG
								className={"framer-l5g3sk"}
								data-framer-name={"Logo"}
								description={"An SVG icon of the Framer Logo."}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"TUFw75aEx"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 8 12"><path d="M 8 0 L 8 4 L 4 4 L 0 0 Z" fill="rgb(255, 255, 255)"></path><path d="M 0 4 L 4 4 L 8 8 L 0 8 Z" fill="rgb(255, 255, 255)"></path><path d="M 0 8 L 4 8 L 4 12 Z" fill="rgb(255, 255, 255)"></path></svg>'
								}
								svgContentId={10150720850}
								title={"Framer Logo"}
								withExternalLayout={true}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-116kl8k"}
								fonts={["Inter-Variable"]}
								layoutDependency={layoutDependency}
								layoutId={"AqAb53yT4"}
								style={{
									"--extracted-1of0zx5": "rgb(255, 255, 255)",
									"--extracted-f6h9gt": '"opsz" 32, "wght" 650',
								}}
								text={mS0YtcEy_2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h2
										style={{
											"--font-selector":
												"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlETXlMQ0FpZDJkb2RDSWdOalV3",
											"--framer-font-family":
												'"Inter Variable", "Inter Variable Placeholder", sans-serif',
											"--framer-font-open-type-features":
												"'cv11' on, 'cv05' on",
											"--framer-font-size": "12px",
											"--framer-font-variation-axes":
												'var(--extracted-f6h9gt, "opsz" 32, "wght" 650)',
											"--framer-letter-spacing": "-0.01em",
											"--framer-line-height": "1em",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-1of0zx5, rgb(255, 255, 255))",
										}}
									>
										{"Framer Expert"}
									</motion.h2>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-fEJfj.framer-1nbf37q, .framer-fEJfj .framer-1nbf37q { display: block; }",
	".framer-fEJfj.framer-9gd1vd { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 7px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 7px 9px 7px 9px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-fEJfj .framer-l5g3sk { flex: none; height: 12px; position: relative; width: 8px; }",
	".framer-fEJfj .framer-116kl8k { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	'.framer-fEJfj[data-border="true"]::after, .framer-fEJfj [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramereBxbj2ci2 = withCSS(Component, css, "framer-fEJfj");
var stdin_default = FramereBxbj2ci2;
FramereBxbj2ci2.displayName = "Framer Badge Base 2";
FramereBxbj2ci2.defaultProps = {
	height: 26,
	width: 110,
};
addPropertyControls(FramereBxbj2ci2, {
	oOze2xTD9: {
		description: "Your Expert profile link. framer.com/@ben/",
		title: "Link",
		type: ControlType.Link,
	},
	mS0YtcEy_: {
		defaultValue: "Framer Expert",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
});
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	FramereBxbj2ci2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:framer-badge-base-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "ivosmmTUd",
		name: "Magyar",
		slug: "hu",
		code: "hu-HU",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a4cf2ba7bf830b43e5f8ed2d8a2bf8e971ecc328736008d3116207e22869c77c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FramerBadgeBase2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a4cf2ba7bf830b43e5f8ed2d8a2bf8e971ecc328736008d3116207e22869c77c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var framer_badge_base_2_default = ComponentWithRoot;
export { framer_badge_base_2_default as default };
